# Generated by Django 5.1 on 2024-08-14 14:07

import django.db.models.deletion
import location_field.models.plain
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tilte', models.CharField(max_length=50)),
                ('price', models.FloatField(max_length=10)),
                ('status', models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale'), ('Buy', 'Buy')], max_length=10)),
                ('sku', models.IntegerField(default=3403, unique=True)),
                ('type', models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Office', 'Office'), ('Land', 'Land'), ('Villa', 'Villa'), ('Shop', 'Shop'), ('Warehouse', 'Warehouse')], max_length=10)),
                ('bathroom', models.IntegerField(blank=True, null=True)),
                ('bedroom', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('parking', models.BooleanField(default=False)),
                ('area', models.FloatField()),
                ('year_built', models.DateField()),
                ('city', models.CharField(max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(default='30.0444,31.2357', max_length=63)),
                ('video', models.FileField(blank=True, null=True, upload_to='prop')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImagesProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='property_images')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ImagesProperty', to='property.property')),
            ],
        ),
        migrations.CreateModel(
            name='FloorPlansImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='property_images')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ImageFloorProperty', to='property.property')),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.CharField(max_length=100)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Features_Property', to='property.property')),
            ],
        ),
    ]
