# Generated by Django 5.1 on 2024-08-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(default='', upload_to='property'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='sku',
            field=models.IntegerField(default=1908, unique=True),
        ),
    ]
