# Generated by Django 5.1 on 2024-08-15 07:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_image_alter_property_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='tilte',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='property',
            name='sku',
            field=models.IntegerField(default=1576, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
