# Generated by Django 5.1 on 2024-08-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_property_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='sku',
            field=models.IntegerField(default=1878, unique=True),
        ),
    ]
