# Generated by Django 5.1 on 2024-08-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_property_view_count_alter_property_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='sku',
            field=models.IntegerField(default=4173, unique=True),
        ),
    ]
