# Generated by Django 5.1 on 2024-09-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_property_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='sku',
            field=models.IntegerField(default=7697, unique=True),
        ),
    ]
