# Generated by Django 5.1 on 2024-10-01 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_alter_property_owner_alter_property_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='sku',
            field=models.IntegerField(default=996, unique=True),
        ),
    ]
