# Generated by Django 5.1 on 2024-10-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_alter_property_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='sku',
            field=models.IntegerField(default=3477, unique=True),
        ),
    ]
