# Generated by Django 5.1 on 2025-04-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_alter_property_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='sku',
            field=models.IntegerField(default=3642, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='year_built',
            field=models.DateField(blank=True, null=True),
        ),
    ]
